make clean
make clean-bin
make PROJECT_NAME="ts0201_tz3000_0x15_zed" PROJECT_DEF="-DBOARD=BOARD_HXDZ_ZBWSD_V02" DEBUG="-DUART_PRINTF_MODE=OFF"

make clean
make PROJECT_NAME="ts0201_tz3000_0x21_zed" PROJECT_DEF="-DBOARD=BOARD_IHSENO_IC_V0" DEBUG="-DUART_PRINTF_MODE=OFF"

make clean
make PROJECT_NAME="ts0201_tz3000_0x22_zed" PROJECT_DEF="-DBOARD=BOARD_ZBEACON" DEBUG="-DUART_PRINTF_MODE=OFF"

make clean
make PROJECT_NAME="ts0201_tz3000_0x23_zed" PROJECT_DEF="-DBOARD=BOARD_ZG_227ZS" DEBUG="-DUART_PRINTF_MODE=OFF"

make clean
make PROJECT_NAME="ts0201_tz3000_0x24_zed" PROJECT_DEF="-DBOARD=BOARD_TH01_ZBEACON" DEBUG="-DUART_PRINTF_MODE=OFF"

make clean
make PROJECT_NAME="ts0201_tz3000_0x28_zed" PROJECT_DEF="-DBOARD=BOARD_Z_WXD" DEBUG="-DUART_PRINTF_MODE=OFF"
