#ifndef SRC_SENSORS_SHT40_H_
#define SRC_SENSORS_SHT40_H_

#if (SENSOR_USED == SENSOR_SHT30)

#define SHT4X_ADDRESS                                       0x44
#define SHT4X_ADDRESS2                                      0x45
#define SHT4X_ADDRESS3                                      0x46

#define SHT4X_MODE_HIGH_PRECISION_WITH_NO_HEATER            0xFD
#define SHT4X_MODE_MEDIUM_PRECISION_WITH_NO_HEATER          0xF6
#define SHT4X_MODE_LOWEST_PRECISION_WITH_NO_HEATER          0xE0
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_200MW_1S      0x39
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_200MW_0P1S    0x32
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_110MW_1S      0x2F
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_110MW_0P1S    0x24
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_20MW_1S       0x1E
#define SHT4X_MODE_HIGH_PRECISION_WITH_HEATER_20MW_0P1S     0x15

typedef enum {
    SHT40_OK = 0,
    SHT40_ERROR,
    SHT40_ERR_NULL_PTR,
    SHT40_ERR_INIT_FAIL,
    SHT40_ERR_COMM_FAIL,
    SHT40_ERR_MODE_FAIL,
    SHT40_ERR_INVALID_LEN,
    SHT40_ERR_DEV_NOT_FOUND,
    SHT40_ERR_ADDR_NOT_FOUND,
    SHT40_ERR_CRC,
    SHT40_ERR_ID,
} sht40_error_t;


#endif /* SENSOR_USED */

#endif /* SRC_SENSORS_SHT40_H_ */
